hystrix:
    dashboard:
        proxy-stream-allow-list: '*'
management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream, info, health
    security:
        enabled: false
spring:
    cloud:
        consul:
            config:
                management:
                    enabled: true
            discovery:
                health-check-interval: 5s
                instanceId: Gateway
        gateway:
            discovery:
                locator:
                    enabled: true
            routes: '[
                {id=serviceA, uri=lb://service-A, predicates=[Path=/srva/**], filters=[RewritePath=/srva/(?<segment>.*),
                /${segment}, {name=Hystrix, args={name=monitor-srvA, fallbackUri=forward:/fallback/serviceA}}]},
                {id=ServiceB, uri=lb://service-B, predicates=[Path=/srvb/**], filters=[RewritePath=/srvb/(?<segment>.*),
                /${segment}, {name=Hystrix, args={name=monitor-srvB, fallbackUri=forward:/fallback/serviceB}}]}]'
